version: "3.7"
services:
  beebot:
    build: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - app-network
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
